### ISSUE TITLE
LowPolyWater Script (NullReferenceException on lines 88,84,84)

### ISSUE THREAD

**Issue by ahmaadaziz** [jp-netsis/LowPolyWater-URP#2]
"NullReferenceException: Object reference not set to an instance of an object
jp.netsis.LowPolyWater.LowPolyWater.Triangulate (netsis.jp.Hexagon.HexagonType hexagonType, UnityEngine.Rect& inHexagonRect, System.Single& hexSize, netsis.jp.Hexagon.HexagonAxialCoordinates[]& pointList) (at Assets/NetsisJp/LowPolyWater/Scripts/LowPolyWater.cs:88)
jp.netsis.LowPolyWater.LowPolyWater.Create () (at Assets/NetsisJp/LowPolyWater/Scripts/LowPolyWater.cs:84)
jp.netsis.LowPolyWater.LowPolyWater.OnValidate () (at Assets/NetsisJp/LowPolyWater/Scripts/LowPolyWater.cs:49)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()"
This is error coming up in the console

**Comment by jp-netsis** [comment]
Thank you for reporting!
OnValidate is called before Awake when launching Unity.
Don't do OnValidate processing when called before Awake.
